# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZenMaster' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZenMaster

 pod 'AFNetworking','~>3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'FDFullscreenPopGesture', '~> 1.1' 
pod 'SDCycleScrollView','~> 1.65’
pod 'WRNavigationBar','~>1.0.9'
pod 'SDAutoLayout', '~> 2.1.3'

end
